### PR TITLE
add dataPath to data channel for client to separate callbacks

### PR DESCRIPTION
**Pull request by grp06**

### CODE REVIEW

**Comment by senluchen2015** [comment]
@narenranjit Without that added attribute "dataPath" there is no way for the front-end to differentiate which path in the data api the channel is returning from. Is there anyway we can create a pre-release of this or is it better to just reference a branch in the project?

**Comment by narenranjit** [comment]
Wouldn't the data-path be whatever was passed in as the first param to subscribe? i.e., i'm imagining something like

``` 
 var channel = cm.getDataChannel('collectionName');
channel.subscribe('foo/bar/actualKey', ()=> {});
```

we'd have to maintain our own path-callback subscription map, where the path is the first param to subscribe. Does that make sense or am I misunderstanding what `dataPath` is here?

**Comment by narenranjit** [comment]
The hard part is going to be matching the string path with the response; i.e. your original response from the server is going to be of the form
```
{ foo: { bar: 1, x: 2} }
```
Assume there are 3 subscribers,
`.subscribe('foo/bar') ` `.subscribe('foo/x')` `.subscribe('foo')`

the first one needs to be called with '1', the second with '2' and the third with `{bar: 1, x:2}` -- i.e. we'd need to translate the slash(or dot or whatever convention) to find the right level of nesting in the object. 

We could probably simplify this somewhat for a first pass by saying you can only subscribe 1 level deep,

**Comment by senluchen2015** [comment]
all dataPath is the path (first parameter) of .subscribe(dataPath). So in .subscribe('foo/bar') it would be 'foo/bar'. The subscribe callback wasn't passing dataPath before, so I think adding it would allow the end user to be able to know which path is being updated.

**Pull request merged**
