### PR TITLE
dms3 version

### PR DESCRIPTION
**Pull request by narenranjit**

### CODE REVIEW

**Comment by mmrj** [comment]
consider adding https://issues.forio.com/browse/EPICENTER-1530 to this branch -- only the "run" api should get prefaced with "v2"

**Comment by narenranjit** [comment]
Wasn't the original decision to keep all the apis at the same version once this goes live?

**Comment by mmrj** [comment]
@narenranjit you're right! thanks for the reminder -- unclear if that got finalized. i'll check with @wglasshusain (on vacation this week).

i logged the epicenter ticket because i was testing the login component and noticed it was trying to call /v2/authentication. not sure if that's supposed to be redirecting and isn't, or what. we'll get back to you.

**Comment by mmrj** [comment]
confirmed in Platform meeting -- we do want to preface everything with /v2/, so no change necessary here. 

we made a platform ticket for the change (including e.g. adding a /v2/ redirect as needed), because it hasn't happened yet in our DMS3 testing servers.

**Comment by mmrj** [comment]
merged! deleting branch

**Pull request merged**
